version: '3'

services:
  server:
    build:
      context: ./server
    ports:
      - 3630:3630
    volumes:
      - ./server:/var/www/html
      - /var/www/html/vendor
    depends_on:
      database:
        condition: service_healthy
  
  client:
    build:
      context: ./client
    command: npm run dev
    ports:
      - 5173:5173
    volumes:
      - type: bind
        source: ./client
        target: /usr/app
      - /usr/app/node_modules
    depends_on:
      - server
  
  database:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5