### Créer un logement avec ses équipements
POST http://localhost:3630/logements/create
Content-Type: application/json
### A FAIRE SUR POSTMAN, PAS POSSIBLE EN FORMAT JSON, METTRE FORMAT MULTIPART FORM-DATA
{
  "name": "Logement 5 Test avec Image",
  "images": ["La_maison_dans_les_bois.jpg", "Exemple.jpg"],
  "secteur": "Rennes",
  "description": "Bel Appartement, vue mer",
  "tarif_bas": 100,
  "tarif_moyen": 150,
  "tarif_haut": 200,
  "m_carre": 150,
  "chambre": 3,
  "salle_de_bain": 2,
  "categorie": "Appart",
  "type": "Type",
  "equipements": [
    {"id": 1},
    {"id": 2}
  ]
}

### Afficher la liste des logements avec leurs équipements ###
GET http://localhost:3630/logements

### Afficher un logement par ID avec ses équipements ###
GET http://localhost:3630/logements/6

### Mettre à jour un logement par ID avec ses équipements ###
PUT http://localhost:3630/logements/8
Content-Type: application/json
### A FAIRE SUR POSTMAN, PAS POSSIBLE EN FORMAT JSON, METTRE FORMAT MULTIPART FORM-DATA
{
  "name": "Updated Logement",
  "images": ["La_Galibe.jpg"],
  "secteur": "updated_secteur",
  "description": "updated_description",
  "tarif_bas": 120,
  "tarif_moyen": 180,
  "tarif_haut": 240,
  "m_carre": 180,
  "chambre": 4,
  "salle_de_bain": 3,
  "categorie": "updated_categorie",
  "type": "updated_type",
  "equipements": [
    {"id": 1},
    {"id": 2},
    {"id": 3},
    {"id": 4}
  ]
}

### Supprimer un logement par ID ###
DELETE http://localhost:3630/logements/10
