### Authentification d'un utilisateur ###

POST http://localhost:3630/auth/login
Content-Type: application/json

{
    "email":"alexandre.buet@institutsolacroup.com",
    "password": "9ffE7xnfPW"
}

### Récupérer les informations de l'utilisateur connecté ###

GET http://localhost:3630/auth/info

### Déconnexion de l'utilisateur ###

GET http://localhost:3630/auth/logout
